'use client'

import { useState } from 'react'
import { AlertTriangle, Bell, CheckCircle2, Users } from 'lucide-react'
import { alertCounts, staffAlerts } from '@/lib/staff-data'
import { AlertFilters, AlertList, PageHeader, PrivacyBadge, Stat } from '@/components/staff/staff-ui'

export default function StaffDashboard() { const [alerts, setAlerts] = useState(staffAlerts); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const filtered = alerts.filter((a) => (status === 'all' || a.status === status) && `${a.kind} ${a.studentName} ${a.id}`.toLowerCase().includes(query.toLowerCase())); function update(id: string, next: typeof alerts[number]['status']) { setAlerts((items) => items.map((a) => a.id === id ? { ...a, status: next } : a)) }
return <><PageHeader eyebrow="Staff dashboard" title="A clearer view of care." description="Review privacy-safe patterns, keep context human, and decide what support may be useful." action={<PrivacyBadge />} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Active students" value="184" detail="82% checked in this week" icon={Users} /><Stat label="New alerts" value={String(alertCounts.new)} detail="Need a first look" icon={Bell} /><Stat label="Follow-up queue" value={String(alertCounts.followUp)} detail="Human support recommended" icon={AlertTriangle} /><Stat label="Reviewed this week" value="31" detail="Audit trail up to date" icon={CheckCircle2} /></div><section className="mt-8 rounded-2xl border border-line bg-white p-5 shadow-card sm:p-7"><div className="mb-5 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Attention queue</p><h2 className="mt-2 font-display text-2xl font-extrabold tracking-[-.05em] text-ink">Patterns worth a human look</h2></div><p className="text-xs font-bold text-muted">Updated just now</p></div><AlertFilters query={query} setQuery={setQuery} status={status} setStatus={setStatus} /><AlertList alerts={filtered} onStatus={update} /></section></> }
