'use client'

import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { AlertTriangle, BarChart3, Bell, Check, ChevronRight, CircleHelp, FileText, LayoutDashboard, LockKeyhole, LogOut, Menu, Search, ShieldCheck, Users, X } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { signOutStaff } from '@/lib/staff-auth'
import { StaffAlert, aggregateTrend } from '@/lib/staff-data'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-UVl8uuOTaBcLektp7EuymOHDIlo7Vt.png'
const nav = [{ href: '/staff/dashboard', label: 'Dashboard', icon: LayoutDashboard }, { href: '/staff/alerts', label: 'Alerts', icon: Bell }, { href: '/staff/insights', label: 'Insights', icon: BarChart3 }, { href: '/staff/students', label: 'Students', icon: Users }, { href: '/staff/privacy', label: 'Privacy', icon: ShieldCheck }]

export function StaffSidebar() {
  const pathname = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false)
  const links = <nav className="flex flex-col gap-1">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition ${pathname.startsWith(href) ? 'bg-yellow text-ink' : 'text-muted hover:bg-ice hover:text-ink'}`}><Icon className="size-4" />{label}</Link>)}</nav>
  return <><button onClick={() => setOpen(true)} className="fixed left-4 top-4 z-40 flex size-10 items-center justify-center rounded-xl border border-line bg-white text-ink shadow-card lg:hidden" aria-label="Open staff navigation"><Menu className="size-5" /></button><aside className="hidden min-h-screen w-64 shrink-0 flex-col border-r border-line bg-white p-5 lg:flex"><Brand /><div className="mt-10">{links}</div><div className="mt-auto rounded-2xl bg-ice p-4"><p className="text-xs font-extrabold uppercase tracking-widest text-muted">Staff preview</p><p className="mt-2 text-sm font-bold text-ink">Minimum necessary access.</p><Link href="/staff/privacy" className="mt-3 inline-flex items-center gap-1 text-xs font-extrabold text-ink">Read privacy guide <ChevronRight className="size-3" /></Link></div><StaffProfile /></aside><AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 bg-ink/30 lg:hidden" onClick={() => setOpen(false)}><motion.aside initial={{ x: -280 }} animate={{ x: 0 }} exit={{ x: -280 }} onClick={(e) => e.stopPropagation()} className="flex h-full w-72 flex-col bg-white p-5"><div className="flex items-center justify-between"><Brand /><button onClick={() => setOpen(false)} aria-label="Close staff navigation"><X className="size-5" /></button></div><div className="mt-10">{links}</div><div className="mt-auto"><StaffProfile /></div></motion.aside></motion.div>}</AnimatePresence></>
}

function Brand() { return <Link href="/staff/dashboard" className="flex items-center gap-2.5"><div className="size-10 overflow-hidden rounded-xl bg-[#1684d6]"><img src={logo} alt="Pingu" className="size-full object-cover" /></div><div><span className="font-display text-xl font-extrabold tracking-[-.06em] text-ink">pingu</span><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-muted">staff portal</p></div></Link> }
function StaffProfile() { const router = useRouter(); return <div className="mt-5 flex items-center justify-between border-t border-line pt-4"><div><p className="text-sm font-extrabold text-ink">Alex Morgan</p><p className="text-xs font-semibold text-muted">Student support</p></div><button onClick={() => { signOutStaff(); router.push('/staff/login') }} aria-label="Sign out"><LogOut className="size-4 text-muted" /></button></div> }

export function StaffShell({ children }: { children: React.ReactNode }) { const pathname = usePathname(); const router = useRouter(); const [ready, setReady] = useState(pathname === '/staff/login'); useEffect(() => { if (pathname === '/staff/login') { setReady(true); return } if (!window.sessionStorage.getItem('pingu-staff-session')) router.replace('/staff/login'); else setReady(true) }, [pathname, router]); if (!ready) return <div className="min-h-screen bg-ice" />; if (pathname === '/staff/login') return <>{children}</>; return <div className="flex min-h-screen bg-ice"><StaffSidebar /><main className="min-w-0 flex-1 px-4 pb-10 pt-20 sm:px-8 lg:px-10 lg:pt-10">{children}</main></div> }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <header className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 font-display text-3xl font-extrabold tracking-[-.06em] text-ink sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{description}</p></div>{action}</header> }
export function PrivacyBadge() { return <span className="inline-flex items-center gap-1.5 rounded-full border border-line bg-white px-3 py-1.5 text-xs font-extrabold text-muted"><LockKeyhole className="size-3.5" /> No private notes</span> }
export function Stat({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: React.ElementType }) { return <section className="rounded-2xl border border-line bg-white p-5 shadow-card"><div className="flex items-center justify-between"><p className="text-sm font-bold text-muted">{label}</p><Icon className="size-4 text-muted" /></div><p className="mt-4 font-display text-3xl font-extrabold tracking-[-.06em] text-ink">{value}</p><p className="mt-1 text-xs font-semibold text-muted">{detail}</p></section> }
export function AlertBadge({ status }: { status: StaffAlert['status'] }) { const labels = { new: 'New', reviewed: 'Reviewed', 'follow-up': 'Needs follow-up', dismissed: 'Dismissed' }; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-extrabold ${status === 'new' ? 'bg-yellow text-ink' : status === 'follow-up' ? 'bg-[#ffe3e8] text-[#9e344a]' : status === 'reviewed' ? 'bg-[#ddf5e7] text-[#277348]' : 'bg-[#eef2f5] text-muted'}`}>{labels[status]}</span> }
export function AlertList({ alerts, onStatus }: { alerts: StaffAlert[]; onStatus?: (id: string, status: StaffAlert['status']) => void }) { return <div className="flex flex-col gap-3">{alerts.map((alert) => <article key={alert.id} className="rounded-2xl border border-line bg-white p-5 shadow-card"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#fff4bf]"><AlertTriangle className="size-4 text-ink" /></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-extrabold text-ink">{alert.kind}</h3><AlertBadge status={alert.status} /></div><p className="mt-1 text-xs font-semibold text-muted">{alert.studentName} · {alert.createdAt}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{alert.reason}</p></div></div><Link href={`/staff/students/${alert.id}`} className="inline-flex shrink-0 items-center gap-1 text-sm font-extrabold text-ink">View trend <ChevronRight className="size-4" /></Link></div>{onStatus && <div className="mt-4 flex flex-wrap gap-2 border-t border-line pt-4"><button onClick={() => onStatus(alert.id, 'reviewed')} className="rounded-full border border-line px-3 py-2 text-xs font-extrabold text-ink hover:border-ink"><Check className="mr-1 inline size-3" />Mark reviewed</button><button onClick={() => onStatus(alert.id, 'follow-up')} className="rounded-full border border-line px-3 py-2 text-xs font-extrabold text-ink hover:border-ink">Needs follow-up</button><button onClick={() => onStatus(alert.id, 'dismissed')} className="rounded-full px-3 py-2 text-xs font-extrabold text-muted hover:bg-ice">Dismiss</button></div>}</article>)}</div> }
export function AlertFilters({ query, setQuery, status, setStatus }: { query: string; setQuery: (v: string) => void; status: string; setStatus: (v: string) => void }) { return <div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-muted" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by alert or student ID" className="h-10 w-full rounded-xl border border-line bg-white pl-9 pr-3 text-sm font-semibold outline-none focus:border-ink" /></label><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-10 rounded-xl border border-line bg-white px-3 text-sm font-bold text-ink outline-none"><option value="all">All statuses</option><option value="new">New</option><option value="follow-up">Needs follow-up</option><option value="reviewed">Reviewed</option><option value="dismissed">Dismissed</option></select></div> }
export function TrendChart({ data = aggregateTrend, dataKey = 'wellbeing' }: { data?: { day: string; wellbeing: number; stress: number; completion?: number }[]; dataKey?: 'wellbeing' | 'stress' | 'completion' }) { return <div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 8, right: 0, left: -28, bottom: 0 }}><defs><linearGradient id={`fill-${dataKey}`} x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#ffd84d" stopOpacity={.55} /><stop offset="95%" stopColor="#ffd84d" stopOpacity={.03} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e1ebf2" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#738291', fontSize: 11, fontWeight: 600 }} /><YAxis hide domain={dataKey === 'stress' ? [0, 5] : [0, 100]} /><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid #dce7ee' }} /><Area type="monotone" dataKey={dataKey} stroke={dataKey === 'stress' ? '#53a9d6' : '#111111'} strokeWidth={3} fill={`url(#fill-${dataKey})`} /></AreaChart></ResponsiveContainer></div> }

export function useFilteredAlerts(alerts: StaffAlert[]) { const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const filtered = useMemo(() => alerts.filter((a) => (status === 'all' || a.status === status) && `${a.kind} ${a.studentName} ${a.id}`.toLowerCase().includes(query.toLowerCase())), [alerts, query, status]); return { query, setQuery, status, setStatus, filtered } }
