'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, LockKeyhole, ShieldCheck } from 'lucide-react'
import { signInStaff } from '@/lib/staff-auth'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-UVl8uuOTaBcLektp7EuymOHDIlo7Vt.png'

export default function StaffLogin() {
  const router = useRouter(); const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  function submit(event: FormEvent) { event.preventDefault(); if (!signInStaff(identifier, password)) return setError('Use any staff ID with the demo password shown below.'); router.push('/staff/dashboard') }
  return <main className="flex min-h-screen items-center justify-center bg-ice px-4 py-10"><div className="grid w-full max-w-4xl overflow-hidden rounded-[2rem] border border-line bg-white shadow-card md:grid-cols-[.9fr_1.1fr]"><section className="hidden bg-ink p-10 text-white md:block"><div className="size-16 overflow-hidden rounded-2xl bg-[#1684d6]"><img src={logo} alt="Pingu" className="size-full object-cover" /></div><p className="eyebrow mt-14 text-white/50">Pingu staff portal</p><h1 className="mt-3 font-display text-4xl font-extrabold leading-tight tracking-[-.06em]">Support starts with noticing.</h1><p className="mt-5 max-w-sm text-sm leading-6 text-white/65">A calm workspace for reviewing privacy-safe patterns and offering human support when it may help.</p><div className="mt-14 flex items-center gap-3 text-sm font-bold text-white/80"><ShieldCheck className="size-5 text-yellow" /> Non-diagnostic by design</div></section><section className="p-7 sm:p-10"><Link href="/login" className="inline-flex items-center gap-2 text-sm font-bold text-muted hover:text-ink"><ArrowLeft className="size-4" /> Back to access</Link><p className="eyebrow mt-8">Welcome back</p><h2 className="mt-2 font-display text-3xl font-extrabold tracking-[-.06em] text-ink">Staff sign in</h2><p className="mt-3 text-sm leading-6 text-muted">Use your approved staff account to access the support workspace.</p><form onSubmit={submit} className="mt-8 flex flex-col gap-5"><label className="flex flex-col gap-2 text-sm font-bold text-ink">Staff ID or email<input value={identifier} onChange={(e) => setIdentifier(e.target.value)} required className="h-12 rounded-xl border border-line bg-[#fbfdff] px-4 font-semibold outline-none focus:border-ink" placeholder="alex@school.edu" /></label><label className="flex flex-col gap-2 text-sm font-bold text-ink">Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required className="h-12 rounded-xl border border-line bg-[#fbfdff] px-4 font-semibold outline-none focus:border-ink" placeholder="••••••••" /></label>{error && <p className="text-sm font-bold text-[#9e344a]">{error}</p>}<button className="mt-2 flex h-12 items-center justify-center gap-2 rounded-xl bg-yellow text-sm font-extrabold text-ink shadow-[0_4px_0_#111]">Continue <LockKeyhole className="size-4" /></button></form><div className="mt-7 rounded-xl bg-ice p-4 text-xs leading-5 text-muted"><strong className="text-ink">Demo access:</strong> any staff ID · password <code className="font-bold text-ink">pingu-staff</code></div><a href="/" className="mt-6 block text-center text-sm font-extrabold text-muted hover:text-ink">Back to student portal</a></section></div></main>
}
